package survey.frontend.panels;

import java.awt.BorderLayout;
import java.awt.HeadlessException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.TableColumn;
import survey.backend.SurveyEngine;
import survey.backend.SurveyEngineException;
import survey.backend.entities.Survey;
import survey.frontend.models.SurveyTableModel;

/**
 *
 * @author Peter Petkanič/433422
 */
public class jPanelMain extends javax.swing.JPanel {

    private final SurveyEngine se;
    
    /**
     * 
     * @param se
     */
    public jPanelMain(SurveyEngine se) {
        this.se = se;
        initComponents();
        updateTable();
    }
    
    private void updateTable(){
        SurveyTableModel model  = (SurveyTableModel) jTableSurveys.getModel();
        model.recreateSurveys(se.getSurveysIdsTitles());
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSurveys = new javax.swing.JTable();
        jButtonCreateSurvey = new javax.swing.JButton();
        jButtonEditSurvey = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        jTableSurveys.setModel(new SurveyTableModel());
        jScrollPane1.setViewportView(jTableSurveys);
        jTableSurveys.setAutoResizeMode( JTable.AUTO_RESIZE_ALL_COLUMNS );
        TableColumn columnA = jTableSurveys.getColumn("ID");
        columnA.setMinWidth(50);
        columnA.setMaxWidth(50);

        jButtonCreateSurvey.setText("Create survey");
        jButtonCreateSurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateSurveyActionPerformed(evt);
            }
        });

        jButtonEditSurvey.setText("Edit survey");
        jButtonEditSurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSurveyActionPerformed(evt);
            }
        });

        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCreateSurvey, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jButtonEditSurvey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreateSurvey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditSurvey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void surveyEditorInit(JPanel panel, String frameName){
        JFrame newFrame = new JFrame(frameName);
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        newFrame.setIconImage(new ImageIcon("src/web/favicon.png").getImage());
        newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newFrame.setLayout(new BorderLayout());
        newFrame.add(panel, BorderLayout.CENTER);
        newFrame.setLocation(topFrame.getX(),topFrame.getY());        
        newFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                updateTable();
                topFrame.setEnabled(true);
            }
        });
        
        topFrame.setEnabled(false);
        newFrame.pack();
        newFrame.setVisible(true);
    }
    
    private void jButtonCreateSurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateSurveyActionPerformed
        surveyEditorInit(new jPanelSurvey(se,new Survey(-1, "", "", null)), "Create survey");
    }//GEN-LAST:event_jButtonCreateSurveyActionPerformed

    private void jButtonEditSurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSurveyActionPerformed
        try {
            SurveyTableModel model = (SurveyTableModel) jTableSurveys.getModel();
            Integer sid = model.getSurveyOnRow(jTableSurveys.getSelectedRow()).getSid();
            
            surveyEditorInit(new jPanelSurvey(se,se.getSurvey(sid)), "Edit survey");
        } catch (SurveyEngineException | HeadlessException | ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Please select survey first!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditSurveyActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        JFrame thisFrame = (JFrame)this.getRootPane().getParent();
        thisFrame.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateSurvey;
    private javax.swing.JButton jButtonEditSurvey;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSurveys;
    // End of variables declaration//GEN-END:variables
}
